global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: proxy-go
    metrics_path: /metrics
    static_configs:
      - targets: ['proxy-go:9090']

  - job_name: api-nest
    metrics_path: /metrics
    static_configs:
      - targets: ['api-nest:3000']

  - job_name: dashboard-nuxt
    metrics_path: /api/metrics
    static_configs:
      - targets: ['dashboard-nuxt:3001']
